ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')), 
    path('contacto/', include('contacto.urls')), 
    path('blog/', include('blog.urls')), 
    path('tienda/', include('tienda.urls')), 
    path('carro/', include('carro.urls')), 
    path('pedidos/', include('pedidos.urls')), 
    path('autenticacion/', include('autenticacion.urls')), 
    path('', include('ProyectoWebApp.urls')), 
] 

blog/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [  
    path('', views.blog, name='Blog'), 
    path('categoria/<categoria_id>/', views.categoria, name='categoria'), 
] 
 

carro/urls.py
from django.urls import path

from . import views 

app_name = 'carro'

urlpatterns = [  
    path('agregar/<producto_id>/', views.agregar_producto, name = "agregar"),  
    path('restar/<producto_id>/', views.restar_producto, name = "restar"),  
    path('eliminar/<producto_id>/', views.eliminar_producto, name = "eliminar"),  
    path('limpiar/', views.limpiar_carro, name = "limpiar"),  
] 
 

tienda/urls.py
from django.urls import path

from . import views 

urlpatterns = [  
    path('', views.tienda, name='Tienda'),  
] 
 

tienda/models.py
from django.db import models 

# Create your models here.
class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50) 
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'categoriaProd'
        verbose_name_plural = 'categoriasProd'
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50) 
    descripcion = models.CharField(max_length=100) 
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='tienda', null=True, blank=True)
    disponibilidad = models.BooleanField(default=True)
    categorias = models.ForeignKey(CategoriaProd, on_delete = models.CASCADE)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'producto'
        verbose_name_plural = 'productos'
    
    def __str__(self):
        return self.nombre

carro/views.py
from .carro import Carro
from tienda.models import Producto
from django.shortcuts import redirect, render

# Create your views here.


def agregar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.agregar(producto)

    return redirect("Tienda")


def eliminar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.eliminar(producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carro.restar(producto)

    return redirect("Tienda")


def limpiar_carro(request):
    carro = Carro(request)
    carro.vaciar()

    return redirect("Tienda")

tienda/views.py
from django.shortcuts import render, HttpResponse
from .models import Producto
# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    return render(request, 'tienda/tienda.html', {"productos":productos})

tienda/templates/carro/widget.html
{% load static%}
<div class="card"style="max-height: 500px; overflow: auto">
  <table class="table table-hover" style="overflow: auto">
    <thead>
      <tr>
        <th colspan="3" class="text-center" scope="col">
          <h4 class="card-title">Carrito</h4>
        </th> 
      </tr>{% if request.session.carro.items %}
      <tr class="text-center">
        <th scope="row">
          <h6 class="card-title">Producto</h6>
        </th>
        <th >
          <h6 class="card-title" >Cantidad</h6>
        </th>
        <th>
          <h6 class="card-title"  >Suma</h6>
        </th>
      </tr>{% endif %}
    </thead>
    <tbody>
      {% if request.session.carro.items %} 
        {% for key, value in request.session.carro.items %}
        <tr class="text-center">
            <td style="max-width: 94.17px;">{{value.nombre}}</td>
            <td>{{value.cantidad}}</td>
            <td>
                <a href="{% url 'carro:restar' value.producto_id %}"class="btn btn-sm btn-primary">-</a>
                {{value.precio}} $
                <a href="{% url 'carro:agregar' value.producto_id %}"class="btn btn-sm btn-primary">+</a>
            </td>
        </tr>
        {% endfor %} 
      {% else %}
        <tr>
            <td colspan="3">
            <div class="alert alert-danger text-center">
                No hay productos agregados
            </div>
            </td>
        </tr>
      {% endif %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">
          <p>Total: {{importe_total_carro}} $</p> 
        </td>
      </tr>
      
      {% if request.session.carro.items %} 
      <tr>
        <td colspan="3" style='text-align:center'>
          <a href="{% url "procesar_pedido" %}"class="btn btn-lg btn-primary btn-block">Comprar</a>
        </td>
      </tr>
      {% endif %}
    </tfoot>
  </table>
</div>